### PR TITLE
Mirage zarith 1.13

### PR DESCRIPTION
**Pull request by hannesm**
This updates the master branch to the zarith release-1.13 tag.

This also rebases the dune+mirage commits on top of the 1.13 release.

It would be great if someone would mind to review them, then we could tag a release and update our version in duniverse/mirage-opam-overlays. WDYT?

### CODE REVIEW

**Comment by hannesm** [comment]
ok, so I created a branch "zarith-1.13" on top off the 1.13 release tag from upstream. And on top of that branch I rebased the existing patches (as seen above). This is now ready for review.

**Review by dinosaure — APPROVED** [review]
Seems correct, as long as we actually can make an unikernel with this version.

**Comment by hannesm** [comment]
Thanks for your review, @dinosaure. I'll later test to construct a unikernel from this branch.

**Comment by hannesm** [comment]
I tested this with the mirage-crypto unikernel that uses zarith. It works nicely with the hvt target. It as well worked nicely with the unix target.

I had to change the order of LIBS and LDFLAGS collected from zarith, so LDFLAGS take precedence. I added a comment to the dune file.

**Comment by hannesm** [comment]
I squashed commits and believe this is ready for merge & release.

**Pull request merged**
